### ISSUE TITLE
No CMAKE_CSharp_COMPILER could be found

### ISSUE THREAD

**Issue by CarlPoirier** [micst/CMake#1] opened 2016-04-01 14:24 UTC
Hi,

I'm trying to compile the https://github.com/micst/CMakeCSharpTest. I first compiled this CMake which I bootstrapped with the upstream CMake.

Then, running this CMake for the CMakeCSharpTest, I get the No CMAKE_CSharp_COMPILER could be found. I however have Visual Studio 11 2012 installed and can successfully create C# projects with it. I added the CMakeOutput.log for reference.

Regards,

Carl

[CMakeOutput.txt](https://github.com/micst/CMake/files/199771/CMakeOutput.txt)

**Comment by micst** [comment] 2016-04-04 06:38
Hi,

the CMakeCSharpTest project is outdated at the moment. The last commit from beginning of July last year was in the middle of implementing the feature. Many things have changed/become easier since then. Have a look at the integrated ctest for C# to see how you can compile C# projects: 

https://github.com/micst/CMake/tree/csharp/Tests/CSharp

I might update the C# test project some time, but it's not on my schedule right now.

**Comment by CarlPoirier** [comment] 2016-04-04 18:11
Hi,

Thanks for the reply. I tried the CSharp test but unfortunately, I get the same error message.

What I simply do is:

> cd CMake-CSharp/Tests/CSharp
> C:\Program \Files\CMake-Csharp\bin\cmake.exe .

**Comment by micst** [comment] 2016-04-05 06:32
Hi,

I cannot reproduce your experience because I have four versions of VS installed beside each other and executing the command you propse will lead me to using VS 2015. What I did is: 
- build cmake debug version (x64) with VS 2012
- add the necessary qt libraries to the "bin\Debug" folder where the executables are
- copy the "Tests\CSharp" directory to my desktop
- run the cmake gui on the CSharp test => worked for me

Can you reproduce your error using the cmake gui?

**Comment by CarlPoirier** [comment] 2016-04-05 17:24
Hi,

Yes I do get the error using the GUI as well. My compiler is located at C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe, we would need a box to indicate it when choosing "specify native compilers".

**Comment by micst** [comment] 2016-04-06 13:01
Ok, at this moment I cannot accurately tell from where the error might come exactly. The compiler detection has to be reworked in some detail as requested from the CMake mailing list:

http://thread.gmane.org/gmane.comp.programming.tools.cmake.devel/15753/focus=16064

I believe once the compiler detection is good enough for upstream, your problem will also be sovled. Unfortunately I don't know when I will find time to do it.

**Comment by CarlPoirier** [comment] 2016-04-06 20:06
Alright, I'll be keeping an eye out on this. Thank you very much for your time and I wish you can get this upstreamed.

**Comment by micst** [comment] 2017-01-24 20:40
With commit f6e4602fe7467fe149f3843a3263a986ea1d804d C# support for cmake has been merged to upstream master branch. This should resolve any discussion about ``.csproj`` support here.

**Closed as completed by micst** 2017-01-24 20:40 UTC
